#name: google-java-format
#
#on: [push, pull_request]
#
#permissions:
#  contents: write
#
#jobs:
#
#  formatting:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: axel-op/googlejavaformat-action@v3 # google-java-format 실행
#        with:
#          args: "--dry-run"
#          skip-commit: true
##          commit-message: "Format : Google Java Format"
#          github-token: ${{ secrets.GH_TOKEN }}
#


name: google-java-format

on: [pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--dry-run --set-exit-if-changed"
          skip-commit: true