name: google-java-format

on: [push, pull_request]

permissions:
  contents: write

jobs:

  formatting:
    if: |
      github.ref == 'refs/heads/dev' || github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Run Google Java Format
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace --aosp"
          commit-message: "[STYLE][Github Action]: Application Of Google Java Format"
          github-token: ${{ secrets.GH_TOKEN }}



#name: google-java-format
#
#on: [pull_request]
#
#jobs:
#  check-formatting:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: axel-op/googlejavaformat-action@v3
#        with:
#          args: "--dry-run --set-exit-if-changed"
#          skip-commit: true