name: google-java-format

on: [pull_request]
jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3 # google-java-format 실행
        with:
          args: "--replace"
          commit-message: "Format : Google Java Format"
          github-token: ${{ secrets.GH_TOKEN }}

